export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GET_USER_ACCOUNTS = 'GET_USER_ACCOUNTS';
export const GET_USER_ACCOUNTS_SUCCESS = 'GET_USER_ACCOUNTS_SUCCESS';

export const GET_TRANSACTIONS_MINI_SUCCESS = 'GET_TRANSACTIONS_MINI_SUCCESS';
export const GET_TRANSACTIONS_BY_AMOUNT_SUCCESS ='GET_TRANSACTIONS_BY_AMOUNT_SUCCESS'
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';